exports.PAYPAL_EVENT_SUBSCRIPTION = {
  BILLING_SUBSCRIPTION_ACTIVATED: "BILLING.SUBSCRIPTION.ACTIVATED",
  BILLING_SUBSCRIPTION_CANCELLED: "BILLING.SUBSCRIPTION.CANCELLED",
  BILLING_SUBSCRIPTION_CREATED: "BILLING.SUBSCRIPTION.CREATED",
  BILLING_SUBSCRIPTION_EXPIRED: "BILLING.SUBSCRIPTION.EXPIRED",
  BILLING_SUBSCRIPTION_SUSPENDED: "BILLING.SUBSCRIPTION.SUSPENDED",
  BILLING_SUBSCRIPTION_UPDATED: "BILLING.SUBSCRIPTION.UPDATED",
  BILLING_SUBSCRIPTION_PAYMENT_FAILED: "BILLING.SUBSCRIPTION.PAYMENT.FAILED",
};

exports.PAYPAL_EVENT_PLAN = {
  BILLING_PLAN_CREATED: "BILLING.PLAN.CREATED",
  BILLING_PLAN_UPDATED: "BILLING.PLAN.UPDATED",
  BILLING_PLAN_ACTIVATED: "BILLING.PLAN.ACTIVATED",
  BILLING_PLAN_DEACTIVATED: "BILLING.PLAN.DEACTIVATED",
  BILLING_PLAN_PRICING_CHANGE_ACTIVATED:
    "BILLING.PLAN.PRICING-CHANGE.ACTIVATED",
};

exports.PAYPAL_STATUS = {
  ACTIVE: 'active',
  INACTIVE: 'inactive',
}

exports.PAYPAL_TENURE_TYPE = {
  REGULAR: 'regular',
  TRIAL: 'trial',
}

exports.PAYPAL_INTERVAL_UNIT = {
  MONTH: 'month',
  DAY: 'day',
  WEEK: 'week',
  YEAR: 'year',
}

// https://developer.paypal.com/docs/integration/direct/rest/currency-codes/
exports.PAYPAL_CURRENCY = {
  'USD': 'USD',
  'AUD': 'AUD',
  'BRL': 'BRL',
  'CAD': 'CAD',
  'CNY': 'CNY',
  'CZK': 'CZK',
  'DKK': 'DKK',
  'EUR': 'EUR',
  'HKD': 'HKD',
  'HUF': 'HUF',
  'ILS': 'ILS',
  'JPY': 'JPY',
  'MYR': 'MYR',
  'MXN': 'MXN',
  'TWD': 'TWD',
  'NZD': 'NZD',
  'NOK': 'NOK',
  'PHP': 'PHP',
  'PLN': 'PLN',
  'GBP': 'GBP',
  'SGD': 'SGD',
  'SEK': 'SEK',
  'CHF': 'CHF',
  'THB': 'THB',
}
